services:
  - type: web
    name: skillswap
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: MONGODB_URI
        value: "mongodb+srv://bilol006:bilol006@cluster0.dcw67cz.mongodb.net/skillswap?appName=Cluster0"
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
